src/User/UserHome/Review/Review.js
src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.js

The Yelp Api request no longer fetching the previous generated food 
completed : 2 hours

Fixed Yelp Api request

---

src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.js

User can now pick the food instead of generated randomly
Completed: 1 hour

Pick the Random Food manually

---

.gitignore
package.json
src/App.test.js
src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.test.js
src/User/UserHome/UserInputFoodChoices/__snapshots__/UserInputFoodChoices.test.js.snap
src/__snapshots__/App.test.js.snap
src/setupTests.js

Jest setup along with Enzyme

---

.gitignore
server/controllers/yelpApi.js

I stored the Yelp API keys in local env. I'll proceed to create a guide that will be posted on Slack shortly.
Hours Spent: 1

Stored Yelp's API keys in local env.

---

.gitignore
package.json
src/User/UserHome/Review/Review.test.js
src/User/UserHome/Review/__snapshots__/Review.test.js.snap
src/User/UserHome/UserHome.test.js
src/User/UserHome/UserProfile/UserProfile.test.js
src/User/UserHome/UserProfile/__snapshots__/UserProfile.test.js.snap
src/User/UserHome/__snapshots__/UserHome.test.js.snap
src/User/UserRoutes.test.js
src/User/__snapshots__/UserRoutes.test.js.snap

Hours Spent: 3
Additional Hours Spent on Debugging for a variety of things: 2
Unit Tests Created:
UserHome
UserProfile
Review
UserRoutes

CHC Unit Tests for the Frontend

---

package.json
server/controllers/apiKeys.js
server/routes/routes.js
server/server.js
server/test/apiKeys.test.js

Hours Spent: 2
Please add your Google Maps API Keys and Firebase Keys to local-env to get this to work.

Added APIs to retreive api keys from the backend.

---

.gitignore
package.json
server/server.js

Hour Spent: 1
Used dotenv to set all the environment variable provided by .env
There's no need to type in "source app-env" now.

Added dotenv to set environment variables before starting the server.

---

src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.js

Hour: 4 hours
Allow user to delete food from food list

delete food items

---

src/Home/Home.test.js
src/Home/Signup/Signup.test.js
src/Home/Signup/__snapshots__/Signup.test.js.snap
src/Home/__snapshots__/Home.test.js.snap

Hours Spent: 1
This hour also includes my time gathering data for presentation.

Added unit tests to Home and Signup

---

package-lock.json
package.json
server/routes/routes.js
server/server.js

Production build

---

.travis.yml
package.json

- Automatic deploy master if pull request branch build successful.

Seng Continuous Delivery

---

.travis.yml
src/Map/googleMaps.js

- Automatic test branch without deploying to production
- Automatic build and deploy when pull request test successful in master.
*Note: Make sure there are no warnings in local before you do a pull request.

Continuous Deployment

---

server.js
server/controllers/yelpApi.js
server/routes/routes.js
server/server.js
server/test/test.js
server/test/yelpApi.test.js
src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.js

Updates:
- Can retrieve reviews on Yelp through /api/yelp/reviews.
- Refactored the routing for the backend.
- Added and updated unit tests for Mocha.
Hours Spent: 3

Chc yelp api

---

.travis.yml

- Deploy to Heroku instead of Firebase Hosting

heroku production

---

client/src/Map/__snapshots__/googleMaps.test.js.snap
client/src/Map/googleMaps.js
client/src/Map/map.css
package-lock.json

Hour: 1
Centered the map to fit card component, and removed unnecessary lines of code in googleMaps.js.
References fix for issue #51

Luis gmapscss

---

client/src/Home/Signup/Signup.js
client/src/Home/Signup/Signup.test.js
client/src/Home/Signup/__snapshots__/Signup.test.js.snap
client/src/User/UserHome/UserProfile/UserProfile.js
client/src/User/UserHome/UserProfile/UserProfile.test.js
client/src/User/UserHome/UserProfile/__snapshots__/UserProfile.test.js.snap

4 hours
Validate user address at sign up page and change address at profile page. 
If the address is validate, the longitude and latitude of the address will be stored in the firebase.
Else, a message will show and indicate invalid address. 
Fixed #48 and #44 
Please review and test both Signup.js and UserProfile.js by using different valid and invalid addresses. See if the code works for you.

Cai-validate address by converting it to longitude and latitude

---

client/package.json
client/src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.js
client/src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.test.js
client/src/User/UserHome/UserInputFoodChoices/__snapshots__/UserInputFoodChoices.test.js.snap

- Added one package is called enzyme-to-json.
- Added some more unit test using enzyme-to-json

Seng more test userinputfoodchoices

---

client/src/App.js
client/src/Home/Home.js
client/src/Home/__snapshots__/Home.test.js.snap
client/src/__snapshots__/App.test.js.snap

Hour spent: 1 
Refactor App component, routing to make it easier to redirect to home page (login page) by removing the render method inside the Home route with unnecessary props variables.

refactor app router

---

client/src/Home/Home.js
client/src/Home/Signup/Signup.js
client/src/Home/Signup/__snapshots__/Signup.test.js.snap
client/src/Home/__snapshots__/Home.test.js.snap
client/src/User/UserHome/UserHome.js
client/src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.js
client/src/User/UserHome/UserInputFoodChoices/__snapshots__/UserInputFoodChoices.test.js.snap
client/src/User/UserHome/UserProfile/UserProfile.js
client/src/User/UserHome/UserProfile/__snapshots__/UserProfile.test.js.snap
client/src/User/UserHome/__snapshots__/UserHome.test.js.snap
client/src/index.js

Hours spent: 4 
Fixed Material-UI deprecated typography variant and raised and contained variant warning on console throughout the whole app.

Gerry material ui deprecation fix

---

server/.gitignore
server/controllers/yelpApi.js

Hours Spent: 5
Updates:
- Increase the number of yelp requests we can make to our app using round robin.
- Logged data to a text file. 
Issues with this Pull Request: I've added more environmental variables so this PR won't work until it gets updated.

Chc yelp round robin

---

client/src/User/UserHome/Zipcode/Zipcode.js

Hours: < 1 (approx 10 mins)
Fixed a very specific bug that occurs when you enter a zip code, then enter something invalid, and then enter the same zip code leading to the same zip code not generating yelp the second time.

Quick Zip Fix

---

client/src/Map/googleMaps.js

Simple fix to the google maps api bug. The bug would not display the places when leaving the google maps to head to a different part of the site and then returning to search the same food.

Fixed Places not loading bug
